### ISSUE TITLE
Changing merge strategy

### ISSUE THREAD

**Issue by Kastrylia** [sharecjs/sharec#298]
Greetings! Is it possible to change merge strategy? I want to fully replace a file when applying new version of the config.

At the moment if I have the following in my main project's .prettierrc.json: 
{
  "tabWidth": 2,
  "test": "test"
}
And the following in the corresponding file in the repo of the updated config:
{
  "test": "test"
}

After installing new package and applying it via "npx sharec" I expect it to be:
{
  "test": "test"
}
But in reality it results in: 
{
  "tabWidth": 2,
  "test": "test"
} 

The package's version is "3.2.1",

**Comment by epszaw** [comment]
Hello! It's possible to do [using hooks](https://sharec.js.org/docs/hooks/). Try to replace `prettier` file by upcoming one in `mergedConfigs`. Just play around context to see all data it has.

**Comment by Kastrylia** [comment]
So, basically, I have to substitute content of <pathOfInstalledConfigPackage>/.prettierrc.json to context.merged[pathOfMyConfigFile] in "After merge" hook, right?

**Comment by Kastrylia** [comment]
Furthermore, is it possible to deliver ".sharecrc.js" within the same config package? Or it should be added manually for every repo that uses the config?

**Comment by epszaw** [comment]
> So, basically, I have to substitute content of ${pathOfInstalledConfigPackage}/.prettierrc.json to context.mergedConfigs[pathOfMyConfigFile] in "After merge" hook, right?

That's right.

> Furthermore, is it possible to deliver ".sharecrc.js" within the same config package? Or the file with hooks should be added manually for every repo that uses the config?

Of course, you can, but updated version will be applied for next merge, not for current one.

**Comment by Kastrylia** [comment]
Ok, so there is .sharercrc.js in my repo's node_modules/my-config. When i do "npx sharec" from the root of my project the hook doesn't work. When I move it to the project's root - everything works well. Is it possible to configure sharec to get hooks from package folder?

**Comment by epszaw** [comment]
At this moment `sharec` supports only root configuration file

**Comment by Kastrylia** [comment]
Much obliged! Have a nice day!
